Update ecr.yml

diff --git a/.github/workflows/ecr.yml b/.github/workflows/ecr.yml
--- a/.github/workflows/ecr.yml
+++ b/.github/workflows/ecr.yml
@@ -69,12 +69,17 @@ jobs:
           CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
           CONTAINER_PORT: ${{ secrets.CONTAINER_PORT }}
           NEW_TG_ARN: ${{ secrets.NEW_TG_ARN }}
-          NEW_ALB_ARN: ${{ secrets.NEW_ALB_ARN }}
+          NEW_ALB_NAME: ${{ secrets.NEW_ALB_NAME }}  # ALB Name here
         run: |
           echo "Updating ECS service with new ALB and TG..."
-          aws ecs update-service \
-            --cluster "$CLUSTER_NAME" \
-            --service "$SERVICE_NAME" \
-            --force-new-deployment \
-            --load-balancers "targetGroupArn=$NEW_TG_ARN,containerName=$CONTAINER_NAME,containerPort=$CONTAINER_PORT" \
-            --region ${{ secrets.AWS_REGION }}
+          if [ -n "$NEW_TG_ARN" ] && [ -n "$NEW_ALB_NAME" ]; then
+            aws ecs update-service \
+              --cluster "$CLUSTER_NAME" \
+              --service "$SERVICE_NAME" \
+              --force-new-deployment \
+              --load-balancers "targetGroupArn=$NEW_TG_ARN,containerName=$CONTAINER_NAME,containerPort=$CONTAINER_PORT,loadBalancerName=$NEW_ALB_NAME" \
+              --region ${{ secrets.AWS_REGION }}
+          else
+            echo "Error: Target Group ARN and ALB Name are required."
+            exit 1
+          fi
